services:
  sample-kafka-consumer:
    container_name: sample-kafka-consumer
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - app-network

networks:
  app-network:
    name: app-network
