services:
  sample-kafka-consumer:
    container_name: sample-kafka-consumer
    build:
      context: ./
      dockerfile: Dockerfile
    image: sample-kafka-consumer:latest
    ports:
      - "8082:8082"
    env_file:
      - ../elastic-start-local/.env
    networks:
      - app-network

networks:
  app-network:
    name: app-network
