server:
  port: 8082

spring:
  data:
    elasticsearch:
      repositories:
        enabled: true

  elasticsearch:
    uris:  https://localhost:9200/
    username: elastic
    password: 7sC0Fa87g3niH1Jc0X0t3mP7

app:
  kafka:
    topic: wikimedia-topic