apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-kafka-consumer-config
  namespace: kubernetes-dashboard
data:
  application.yaml: |-
    server:
      port: 8082

    spring:
      kafka:
        consumer:
          bootstrap-servers: kafka-service.kafka.svc.cluster.local:9092
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          group-id: wikimedia-consumer-group
          auto-offset-reset: latest

      data:
        elasticsearch:
          repositories:
            enabled: true

      elasticsearch:
        uris: https://elasticsearch-dev-es-http.elasticsearch.svc.cluster.local:9200
        username: elastic
        password: ${ELASTIC_PASSWORD}

    app:
      kafka:
        topic: wikimedia-topic