apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-binding
  namespace: elasticsearch
subjects:
  - kind: ServiceAccount
    name: kafka-app-sa
    namespace: kafka-apps
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io