apiVersion: v1
kind: Service
metadata:
  name: sample-kafka-consumer
  namespace: kafka-apps
  labels:
    app: sample-kafka-consumer
spec:
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    app: sample-kafka-consumer
  type: ClusterIP